### ISSUE TITLE
Add support for linux-aarch64

### ISSUE THREAD

**Issue by abey79** [conda-forge/binaryen-feedstock#67]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Add support for a linux-aarch64 build.

### Installed packages

```shell
binaryen==117
```

### Environment info

```shell
pixi 0.16.1
```

**Comment by jakirkham** [comment]
Done in PR: https://github.com/conda-forge/binaryen-feedstock/pull/68
